export default {
  P_GetUser: 'P_GetUser',
  P_NewUser: 'P_NewUser',
  P_SetUser: 'P_SetUser',
  P_ProspectusDetails: 'P_ProspectusDetails',
  P_AddressDetail: 'P_AddressDetail',
  P_DesignationDetails: 'P_DesignationDetails',
  P_BasicTableDetails: 'P_BasicTableDetails',
  P_AddNewEmployee: 'P_AddNewEmployee_V1',
  Proc_DocumentRequired: 'Proc_DocumentRequired',
  Proc_DocumentList: 'Proc_DocumentList',
  Proc_required_document_list: 'Proc_required_document_list',
  P_uploadFormFiles: 'P_uploadFormFiles_V1',
  P_FileDetailsFormWise: 'P_FileDetailsFormWise_V1',
  P_EducationDetails: 'P_EducationDetails_V1',
  P_LanguageDetails: 'P_LanguageDetails_V1',
  P_CivilianDetails: 'P_CivilianDetails',
  P_ExManExpDetails: 'P_ExManExpDetails_V1',
  P_EsiServerDetails: 'P_EsiServerDetails_V1',
  P_FamilyDetails: 'P_FamilyDetails',
  P_PhysicalDetails: 'P_PhysicalDetails_V1',
  P_BankDetails: 'P_BankDetails',
  P_getFeeBatchAndSchemeDetails: 'P_getFeeBatchAndSchemeDetails',
  P_GetFormMasterList: 'P_GetFormMasterList',
  P_GetTempDeploymentFormList: 'P_GetTempDeploymentFormList',
  P_GetUnApprovedDocuments: 'P_GetUnApprovedDocuments',
  P_GetTempDeploymentApplicationDetails:
    'P_GetTempDeploymentApplicationDetails',
  p_updateTempDeploymentDocStatus: 'p_updateTempDeploymentDocStatus',
  P_EmployeeBasicDetails: 'P_EmployeeBasicDetails_V1',
  P_GetEduLangDetails: 'P_GetEduLangDetails',
  P_GetExpExMEsiDetails: 'P_GetExpExMEsiDetails',
  P_UpdateFormStatus: 'P_UpdateFormStatus',
  P_SetFileSequence: 'P_SetFileSequence',
  P_GetFileSequence: 'P_GetFileSequence',
  P_GetFileDetails: 'P_GetFileDetails',
  P_GetBankDetailIFSCCodeWise: 'P_GetBankDetailIFSCCodeWise',
  P_ScoreMaster: 'P_ScoreMaster',
  P_CondonationDetail: 'P_CondonationDetail',
  P_ScoreDetails: 'P_ScoreDetails',
  P_CandidateFingerPrint: 'P_CandidateFingerPrint',
  P_getReasonList: 'P_getReasonList',
  P_RqccDetails: 'P_RqccDetails',
  P_RqccDocumentDetail: 'P_RqccDocumentDetail',
  P_OtpDetails: 'P_OtpDetails_V1',
  P_getFormNo: 'Proc_FormNo',
  P_GetCandidateTypeMaster: 'P_GetCandidateTypeMaster',
  P_GetList: 'P_GetList',
  P_GetFormListRoleWise: 'P_GetFormListRoleWise',
  P_GetEsiVerificationFormList: 'P_GetEsiVerificationFormList',
  P_UpdateApprovalStatus: 'P_UpdateApprovalStatus',
  P_UpdateEmployeeDetails: 'P_UpdateEmployeeDetails',
  P_FormStatusDetails: 'P_FormStatusDetails',
  P_UpdateAllFormStatus: 'P_UpdateAllFormStatus',
  P_UpdateEmployeePicDetails: 'P_UpdateEmployeePicDetails_V1',
  P_GetFilteredFormStatusDetails: 'P_GetFilteredFormStatusDetails',
  P_UserDetails: 'P_UserDetails',
  P_IsExistUser: 'P_IsExistUser',
  P_AssessmentDetails: 'P_AssessmentDetails',
  P_getCondoDetails: 'P_getCondoDetails',
  P_GetRequiredDocument: 'P_GetRequiredDocument',
  P_GetApplicableDocType: 'P_GetApplicableDocType',
  P_GetDocumentVerification: 'P_GetDocumentVerification',
  P_UpdateUploadedFileList: 'P_UpdateUploadedFileList',
  P_GetEmpDetailForRegNo: 'P_GetEmpDetailForRegNo_Core_V1',
  P_BranchMaster: 'P_BranchMaster',
  P_RoleMaster: 'P_RoleMaster',
  P_UserBranchPermission: 'P_UserBranchPermission',
  P_GetIndustryList: 'P_GetIndustryList',
  P_CheckBasicDetails: 'P_Checkbasicdetails',
  P_UpdateRegNo: 'P_UpdateRegNo',
  P_GetCardPrintDetails: 'P_GetCardPrintDetails',
  P_UserWiseBranchList: 'P_UserWiseBranchList',
  P_SearchedApplications: 'P_SearchedApplications',
  P_DocumentManagement: 'P_DocumentManagement',
  P_UserManagement: 'P_UserManagement',
  Proc_BranchMaster: 'Proc_BranchMaster',
  P_DocumentMaster: 'P_DocumentMaster',
  P_DesignationMaster: 'P_DesignationMaster',
  P_SchemeMaster: 'P_SchemeMaster',
  P_Error: 'P_Error',
  P_UpdateApprovalStatusDetails: 'P_UpdateApprovalStatusDetails',
  P_GetUploadedFiles: 'P_GetUploadedFiles',
  P_SetLogedInStatus: 'P_SetLogedInStatus',
  P_SetFormStatusDetailsIfExempted: 'P_SetFormStatusDetailsIfExempted',
  P_GetHoDashboardList: 'P_GetHoDashboardList',
  P_GetActiveBranchList: 'P_GetActiveBranchList',
  P_GetAllBranchCameraDetails: 'P_GetAllBranchCameraDetails',
  P_UpdateExpemptedSteps: 'P_UpdateExpemptedSteps',
  P_GetFilteredHODashboardData: 'P_GetFilteredHODashboardData_new',
  P_GetLiveCameraDetails: 'P_GetLiveCameraDetails',
  P_getReportList: 'P_getReportList',
  P_CameraStatus: 'P_CameraStatus',
  P_UANStatusDetail: 'P_UANStatusDetail',
  P_CardPrint: 'P_CardPrint',
  P_GetICardStatus: 'P_GetICardStatus',
  P_Get_State_Master: 'P_Get_State_Master',
  P_Get_Constituency_Detail: 'P_Get_Constituency_Detail',
  P_OTP_Validity: 'P_OTP_Validity_V1',
  P_ApproveRejectRqccElectronicDetail: 'P_ApproveRejectRqccElectronicDetail',
  P_TempDeployment: 'P_TempDeployment',
  P_GetBMIDetails: 'P_GetBMIDetails',
  P_VendorActivity: 'p_vendorActivity',
  P_MachineLog:'p_machine_log',
  P_UpdateBmiDataFromMachine:'P_update_bmi_data_from_machine',
  P_MachinePwd: 'p_machinePwd',
  P_MachinePwdReset:'p_machinePwdReset',
  P_UserDataMeasurement: 'p_User_Data_Measurement',
  P_GetEmployeeDetail:'P_GetEmployeeDetail',

  //---------------------------------For ERP
  P_ERP_AddNewEmployee: 'P_ERP_AddNewEmployee',
  P_Get_ERP_FormMasterList: 'P_Get_ERP_FormMasterList',
  P_ERP_EmployeeBasicDetails: 'P_ERP_EmployeeBasicDetails',
  P_ERP_UpdateUploadedFileList: 'P_ERP_UpdateUploadedFileList',
  P_ERP_GetUploadedFiles: 'P_ERP_GetUploadedFiles',
  P_ERP_GetRequiredDocument: 'P_ERP_GetRequiredDocument',
  P_ERP_uploadFormFiles: 'P_ERP_uploadFormFiles',
  P_ERP_UpdateFormStatus: 'P_ERP_UpdateFormStatus',
  P_ERP_EducationDetails: 'P_ERP_EducationDetails',
  P_ERP_LanguageDetails: 'P_ERP_LanguageDetails',
  P_ERP_OtpDetails: 'P_ERP_OtpDetails',
  P_Get_ERP_EduLangDetails: 'P_Get_ERP_EduLangDetails',
  P_ERP_CivilianDetails: 'P_ERP_CivilianDetails',
  P_Erp_ExManExpDetails: 'P_Erp_ExManExpDetails',
  P_ERP_EsiServerDetails: 'P_ERP_EsiServerDetails',
  P_ERP_AssessmentDetails: 'P_ERP_AssessmentDetails',
  P_Get_ERP_ExpExMEsiDetails: 'P_Get_ERP_ExpExMEsiDetails',
  P_ERP_PhysicalDetails: 'P_ERP_PhysicalDetails',
  P_ERP_UpdateEmployeePicDetails: 'P_ERP_UpdateEmployeePicDetails',
  P_ERP_CandidateFingerPrint: 'P_ERP_CandidateFingerPrint',
  P_Get_ERP_FileSequence: 'P_Get_ERP_FileSequence',
  P_ERP_FileDetailsFormWise: 'P_ERP_FileDetailsFormWise',
  P_ERP_FamilyDetails: 'P_ERP_FamilyDetails',
  P_ERP_BankDetails: 'P_ERP_BankDetails',
  P_Get_ERP_CardPrintDetails: 'P_Get_ERP_CardPrintDetails',
  P_ERP_RqccDocumentDetail: 'P_ERP_RqccDocumentDetail',
  P_ERP_CondonationDetail: 'P_ERP_CondonationDetail',
  P_ERP_ScoreMaster: 'P_ERP_ScoreMaster',
  P_ERP_ScoreDetails: 'P_ERP_ScoreDetails',
  P_ERP_Checkbasicdetails: 'P_ERP_Checkbasicdetails',
  P_OTP_Validity_ERP: 'P_OTP_Validity_ERP',
  P_Erp_ApproveRejectRqccElectronicDetail:
    'P_Erp_ApproveRejectRqccElectronicDetail',

  P_Employee_History: 'P_Employee_History',
  P_CheckExistanceOfRegNo: 'P_CheckExistanceOfRegNo',
  P_AddErpEmployee: 'P_AddErpEmployee',

  P_GetArkData: 'P_GetArkData_V1',
  P_PostArkData: 'P_PostArkData',
  P_Web_App_Token: 'P_Web_App_Token',
  P_Web_App_Token_Update: 'P_Web_App_Token_Update',
  P_Add_prospectus: 'P_Add_prospectus',
  P_TA_TC_BatchMaster_update: 'P_TA_TC_BatchMaster_update',
  P_TrainingFeeMaster_update: 'P_TrainingFeeMaster_update',

  P_BankIFSCMaster_update: 'P_BankIFSCMaster_update',
  P_DesignationMaster_update: 'P_DesignationMaster_update',
  P_DistrictMaster_update: 'P_DistrictMaster_update',
  P_StateMaster_update: 'P_StateMaster_update',
  P_CityMaster_update: 'P_CityMaster_update',
  P_BranchMaster_update: 'P_BranchMaster_update',
  P_UnitMaster_update: 'P_UnitMaster_update',
  P_Prospectus_Status: 'P_Prospectus_Status',
  P_PincodeMaster_update: 'P_PincodeMaster_update',
  Proc_machines:'Proc_machines',
  proc_started_machine:'proc_started_machine',
  p_new_recruitment:'p_new_recruitment'
};
